# Generated by Django 5.2.11 on 2026-02-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('guide_eyebrow', models.CharField(blank=True, max_length=100)),
                ('guide_heading', models.CharField(blank=True, max_length=200)),
                ('guide_description', models.TextField(blank=True)),
                ('guide_image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Guide Page',
                'verbose_name_plural': 'Guide Pages',
            },
            bases=('pages.page',),
        ),
    ]
