# Generated by Django 5.2.11 on 2026-02-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processpage',
            name='process_description',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='process_eyebrow',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='process_heading',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='quality_gate_label',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='quality_gate_text',
        ),
        migrations.CreateModel(
            name='HeaderSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='How We Work', max_length=100)),
                ('heading', models.CharField(blank=True, default='The 7-Step TrustBuild Roadmap', max_length=200)),
                ('description', models.TextField(blank=True, default="Construction in Kenya doesn't have to be chaotic. We use a standardized corporate workflow to ensure predictable results every time.")),
                ('process_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_header', to='process.processpage')),
            ],
            options={
                'verbose_name': 'Process Header',
                'verbose_name_plural': 'Process Headers',
            },
        ),
        migrations.CreateModel(
            name='ProcessCTA',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, default='Ready to take step one?', max_length=200)),
                ('process_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_cta_sections', to='process.processpage')),
            ],
            options={
                'verbose_name': 'Process CTA',
                'verbose_name_plural': 'Process CTAs',
            },
        ),
        migrations.CreateModel(
            name='ProcessSteps',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_gate_label', models.CharField(blank=True, default='Quality Gate', max_length=100)),
                ('quality_gate_text', models.TextField(blank=True, default='This stage must be signed off by both our lead engineer and the client before proceeding.')),
                ('process_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps_sections', to='process.processpage')),
            ],
            options={
                'verbose_name': 'Process Steps Section',
                'verbose_name_plural': 'Process Steps Sections',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('process_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='process.processsteps')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
