# Generated by Django 5.2.11 on 2026-02-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_remove_processpage_process_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcta',
            name='button_link',
            field=models.CharField(blank=True, default='#contact', max_length=200),
        ),
        migrations.AddField(
            model_name='processcta',
            name='button_text',
            field=models.CharField(blank=True, default='Book Initial Consultation', max_length=100),
        ),
    ]
