# Generated by Django 5.2.11 on 2026-02-24 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_processcta_button_link_processcta_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersection',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processcta',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processsteps',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
