# Generated by Django 5.2.11 on 2026-02-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body',
        ),
        migrations.RemoveField(
            model_name='page',
            name='introduction',
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='SVG icon code or icon class', max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost'), ('accent', 'Accent')], default='primary', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_external', models.BooleanField(default=False, help_text='Open in new tab')),
                ('is_full_width', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
