# Generated by Django 5.2.11 on 2026-02-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_body_remove_page_introduction_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='id',
        ),
        migrations.AddField(
            model_name='button',
            name='uuid',
            field=models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
