# Generated by Django 5.2.11 on 2026-02-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_button_id_button_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='seo_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='seo_title',
            new_name='meta_title',
        ),
    ]
