# Generated by Django 5.2.11 on 2026-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_seo_description_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='object_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
