# Generated by Django 5.2.11 on 2026-02-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_button_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='content_reference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
