# Generated by Django 5.2.11 on 2026-02-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('contact_eyebrow', models.CharField(blank=True, max_length=100)),
                ('contact_heading', models.CharField(blank=True, max_length=200)),
                ('contact_description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
            bases=('pages.page',),
        ),
    ]
