# Generated by Django 5.2.11 on 2026-02-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_rename_seo_description_page_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContentSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, default='Contact Information', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('new_project', 'New Project Inquiry'), ('diaspora', 'Diaspora Consultation'), ('partnership', 'Partnership Proposal'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='+254 712 345 678', max_length=100)),
                ('value', models.CharField(blank=True, default='info@trustbuildurban.co.ke', max_length=100)),
                ('icon', models.TextField()),
                ('map_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.808!2d36.8219!3d-1.2921!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMsKwMTcnMjAuMCJTIDM2wrA0OScxMS4wIkU!5e0!3m2!1sen!2ske!4v1234567890', max_length=500)),
                ('map_label', models.CharField(blank=True, default='Office Location', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info_items', to='contact.contactcontentsection')),
            ],
            options={
                'verbose_name': 'Contact Content Section',
                'verbose_name_plural': 'Contact Content Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='Get In Touch', max_length=100)),
                ('heading', models.CharField(blank=True, default="Let's Build Your Legacy Together.", max_length=200)),
                ('description', models.TextField(blank=True, default="Whether you're in the diaspora or local, we're here to provide the radical transparency and excellence your project deserves.")),
                ('contact_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_section', to='contact.contactpage')),
            ],
            options={
                'verbose_name': 'Contact Header',
                'verbose_name_plural': 'Contact Headers',
            },
        ),
        migrations.AddField(
            model_name='contactcontentsection',
            name='contact_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_section', to='contact.contactpage'),
        ),
    ]
