# Generated by Django 5.2.11 on 2026-02-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactcontentsection_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
