# Generated by Django 5.2.11 on 2026-02-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='services_description',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='services_eyebrow',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='services_heading',
        ),
        migrations.CreateModel(
            name='ServicesHeader',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='What We Do', max_length=100)),
                ('heading', models.CharField(blank=True, default='Specialized Solutions for Discerning Clients.', max_length=200)),
                ('description', models.TextField(blank=True, default="From the first site visit to the final coat of paint, we manage the complexities of construction so you don't have to.")),
                ('service_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_section', to='services.servicepage')),
            ],
            options={
                'verbose_name': 'Services Header',
                'verbose_name_plural': 'Services Headers',
            },
        ),
        migrations.CreateModel(
            name='ServicesListSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learn_more_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_sections', to='services.servicepage')),
            ],
            options={
                'verbose_name': 'Services List Section',
                'verbose_name_plural': 'Services List Sections',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True, help_text='SVG icon code')),
                ('link', models.CharField(blank=True, default='/contact', max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_images', to='images.image')),
                ('services_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.serviceslistsection')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
