# Generated by Django 5.2.11 on 2026-02-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='blog_description',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='blog_eyebrow',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='blog_heading',
        ),
        migrations.CreateModel(
            name='BlogGridSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_more_text', models.CharField(blank=True, default='Read More', max_length=100)),
                ('blog_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Blog Grid Section',
                'verbose_name_plural': 'Blog Grid Sections',
            },
        ),
        migrations.CreateModel(
            name='BlogHeader',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='Building Trends', max_length=100)),
                ('heading', models.CharField(blank=True, default='TrustBuild Insights', max_length=200)),
                ('description', models.TextField(blank=True, default='Stay updated with the latest in Kenyan construction, architectural trends, and diaspora investment strategies.')),
                ('blog_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_section', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Blog Header',
                'verbose_name_plural': 'Blog Headers',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='Construction', max_length=100)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('blog_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.bloggridsection')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_images', to='images.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
