# Generated by Django 5.2.11 on 2026-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpage_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
