# Generated by Django 5.2.11 on 2026-02-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('hero_tagline', models.CharField(blank=True, max_length=200)),
                ('hero_heading', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('cta_primary_text', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100)),
                ('happy_customers_value', models.CharField(blank=True, max_length=20)),
                ('property_sales_value', models.CharField(blank=True, max_length=20)),
                ('award_winning_value', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('pages.page',),
        ),
    ]
