# Generated by Django 5.2.11 on 2026-02-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='award_winning_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='happy_customers_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_tagline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='property_sales_value',
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('heading_main', models.CharField(blank=True, max_length=200)),
                ('heading_highlight', models.CharField(blank=True, max_length=100)),
                ('heading_suffix', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.URLField(blank=True, max_length=500)),
                ('background_video', models.URLField(blank=True, max_length=500)),
                ('overlay_opacity', models.IntegerField(default=50, help_text='Overlay opacity percentage (0-100)')),
                ('show_verified_badge', models.BooleanField(default=True)),
                ('verified_text', models.CharField(default='Verified', max_length=50)),
                ('show_live_tracking', models.BooleanField(default=True)),
                ('live_tracking_text', models.CharField(default='Live Project Tracking', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_location', models.CharField(blank=True, max_length=100)),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
