# Generated by Django 5.2.11 on 2026-02-23 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_homepage_award_winning_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, help_text='SVG icon code', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='background_video',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='id',
        ),
        migrations.AddField(
            model_name='herosection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='uuid',
            field=models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
