# Generated by Django 5.2.11 on 2026-02-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_stats_remove_herosection_background_video_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sections', to='images.image'),
        ),
        migrations.AddField(
            model_name='stats',
            name='hero_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='homepage.herosection'),
        ),
    ]
