# Generated by Django 5.2.11 on 2026-02-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_herosection_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ('order',), 'verbose_name': 'Stat', 'verbose_name_plural': 'Stats'},
        ),
        migrations.RemoveField(
            model_name='stats',
            name='icon',
        ),
        migrations.AlterField(
            model_name='stats',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
