# Generated by Django 5.2.11 on 2026-02-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_stats_options_remove_stats_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_text', models.TextField(blank=True, default='Integrity and innovation in every structure we touch. Engineering excellence from the ground up.')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Stats Section',
                'verbose_name_plural': 'Stats Sections',
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('total_reviews', models.CharField(blank=True, default='12,000+', max_length=20)),
                ('label_text', models.CharField(blank=True, default='Client Reviews', max_length=100)),
                ('button_text', models.CharField(blank=True, default='Discover Excellence', max_length=100)),
                ('button_link', models.CharField(blank=True, default='#', max_length=200)),
                ('stats_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='homepage.statssection')),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
            },
        ),
    ]
