# Generated by Django 5.2.11 on 2026-02-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_stats_section_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='statssection',
            name='landmark_projects_label_text',
            field=models.CharField(blank=True, default='Landmark Projects', max_length=100),
        ),
        migrations.AddField(
            model_name='statssection',
            name='landmark_projects_value',
            field=models.CharField(blank=True, default='850', max_length=20),
        ),
    ]
