# Generated by Django 5.2.11 on 2026-02-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_add_landmark_projects_fields'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasporaSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='The Diaspora Challenge', max_length=100)),
                ('heading', models.TextField(blank=True, default='Building in Kenya should not be a gamble.')),
                ('attribution', models.TextField(blank=True, default='TrustBuildUrban was founded to replace fear with structured, world-class building standards.')),
                ('featured_label', models.CharField(blank=True, default='Featured Project', max_length=100)),
                ('featured_title', models.CharField(blank=True, default='The Grand Residence, Runda', max_length=200)),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaspora_featured_images', to='images.image')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaspora_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Diaspora Section',
                'verbose_name_plural': 'Diaspora Sections',
            },
        ),
        migrations.CreateModel(
            name='DiasporaChallenge',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('diaspora_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='homepage.diasporasection')),
            ],
            options={
                'verbose_name': 'Diaspora Challenge',
                'verbose_name_plural': 'Diaspora Challenges',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='The TrustBuildUrban Standard', max_length=100)),
                ('heading', models.TextField(blank=True, default='Why Hundreds of Diaspora Families Trust Us')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Sections',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.TextField(blank=True, help_text='SVG icon code')),
                ('features_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.featuressection')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.TextField(blank=True, default='Free Diaspora Home Building Guide')),
                ('description', models.TextField(blank=True, default='Download our comprehensive manual on navigating land laws, approvals, and construction costs in Kenya from abroad.')),
                ('placeholder', models.CharField(blank=True, default='Enter your email', max_length=100)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Newsletter Section',
                'verbose_name_plural': 'Newsletter Sections',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(blank=True, default='Our Specializations', max_length=100)),
                ('heading', models.TextField(blank=True, default='Elite Engineering & Architectural Excellence')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Sections',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True, help_text='SVG icon code')),
                ('expertise', models.TextField(blank=True, help_text='Comma-separated list of expertise areas')),
                ('services_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homepage.servicessection')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepsSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='Transparent Execution', max_length=100)),
                ('heading', models.TextField(blank=True, default='Our 7-Step Architectural Journey')),
                ('description', models.TextField(blank=True, default='A meticulously structured process from initial concept to the day we hand over your keys.')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Steps Section',
                'verbose_name_plural': 'Steps Sections',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('steps_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='homepage.stepssection')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
