# Generated by Django 5.2.11 on 2026-02-24 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_diasporasection_diasporachallenge_featuressection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroButton',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='SVG icon code or icon class', max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost'), ('accent', 'Accent')], default='primary', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_external', models.BooleanField(default=False, help_text='Open in new tab')),
                ('is_full_width', models.BooleanField(default=False)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='homepage.herosection')),
            ],
            options={
                'verbose_name': 'Hero Button',
                'verbose_name_plural': 'Hero Buttons',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterButton',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='SVG icon code or icon class', max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('ghost', 'Ghost'), ('accent', 'Accent')], default='primary', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_external', models.BooleanField(default=False, help_text='Open in new tab')),
                ('is_full_width', models.BooleanField(default=False)),
                ('newsletter_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='homepage.newslettersection')),
            ],
            options={
                'verbose_name': 'Newsletter Button',
                'verbose_name_plural': 'Newsletter Buttons',
            },
        ),
    ]
