# Generated by Django 5.2.11 on 2026-02-24 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_stats_and_update_clientreview'),
        ('images', '0006_alter_image_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSection',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(blank=True, default='TRUSTBUILD URBAN BY THE NUMBERS', max_length=100)),
                ('background_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_backgrounds', to='images.image')),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats_section', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Stats Section',
                'verbose_name_plural': 'Stats Sections',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, default='500+', max_length=20)),
                ('subtitle', models.CharField(blank=True, default='Projects Completed', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stats_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='homepage.statssection')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='Who We Are', max_length=100)),
                ('heading', models.TextField(blank=True, default='Committed, client-focused, and process-driven builders.')),
                ('description', models.TextField(blank=True, default='We deliver world-class construction services with a focus on quality, transparency, and client satisfaction.')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('button_link', models.CharField(blank=True, default='/about', max_length=200)),
                ('background_image_url', models.URLField(blank=True, max_length=500)),
                ('overlay_opacity', models.IntegerField(default=40, help_text='Overlay opacity percentage (0-100)')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_we_are_sections', to='images.image')),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who_we_are_section', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Who We Are Section',
                'verbose_name_plural': 'Who We Are Sections',
            },
        ),
    ]
