# Generated by Django 5.2.11 on 2026-02-24 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_statssection_stat_whowearesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolioSection',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='Our Work', max_length=100)),
                ('heading', models.TextField(blank=True, default='A Glimpse of Our Architectural Excellence')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Portfolio Section',
                'verbose_name_plural': 'Portfolio Sections',
            },
        ),
    ]
