# Generated by Django 5.2.11 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_portfoliosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='button_link',
            field=models.CharField(blank=True, default='/portfolio', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='button_text',
            field=models.CharField(blank=True, default='View Portfolio', max_length=100),
        ),
    ]
