# Generated by Django 5.2.11 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_portfoliosection_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='description',
            field=models.TextField(blank=True, default='Luxury and family homes delivered across the country.'),
        ),
    ]
