# Generated by Django 5.2.11 on 2026-02-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
    ]
