# Generated by Django 5.2.11 on 2026-02-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('images', '0002_remove_generic_relation_and_usage_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_usages', to='contenttypes.contenttype')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='images.image')),
            ],
            options={
                'verbose_name': 'Image Usage',
                'verbose_name_plural': 'Image Usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='images_imag_content_346bd6_idx'), models.Index(fields=['image'], name='images_imag_image_i_2d5a3c_idx')],
                'unique_together': {('content_type', 'object_id', 'image')},
            },
        ),
    ]
