# Generated by Django 5.2.11 on 2026-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imageusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageusage',
            name='object_id',
            field=models.CharField(max_length=40),
        ),
    ]
