# Generated by Django 5.2.11 on 2026-02-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('images', '0004_alter_imageusage_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageusage',
            name='content_reference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageusage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_usages', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='imageusage',
            name='object_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
