# Generated by Django 5.2.11 on 2026-02-24 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imageusage_content_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
