# Generated by Django 5.2.11 on 2026-02-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_alter_image_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
    ]
