# Generated by Django 5.2.11 on 2026-02-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0007_remove_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name of the company.', max_length=200)),
                ('trading_name', models.CharField(blank=True, help_text='Brand / trading name if different from legal name (e.g. TrustBuild Urban).', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number (e.g. Kenya Companies Registry).', max_length=100)),
                ('tax_identification_number', models.CharField(blank=True, help_text='KRA PIN / Tax ID.', max_length=100)),
                ('vat_number', models.CharField(blank=True, help_text='VAT registration number if applicable.', max_length=100)),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, help_text='Year the company was incorporated.', null=True)),
                ('company_type', models.CharField(blank=True, help_text='e.g. Limited Liability Company, Partnership, Sole Proprietorship.', max_length=100)),
                ('country_of_incorporation', models.CharField(blank=True, default='Kenya', max_length=100)),
                ('physical_address', models.TextField(blank=True, help_text='Full street / building address.')),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('po_box', models.CharField(blank=True, help_text='e.g. P.O. Box 12345-00100, Nairobi', max_length=100, verbose_name='P.O. Box')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Office/HQ latitude (right-click on Google Maps → copy coordinates).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo_primary', 'Primary Logo'), ('logo_secondary', 'Secondary / Alternative Logo'), ('logo_white', 'White / Reversed Logo'), ('logo_dark', 'Dark Logo'), ('favicon', 'Favicon'), ('office_photo', 'Office Photo'), ('team_photo', 'Team Photo'), ('accreditation', 'Accreditation / Certificate Badge'), ('award', 'Award'), ('other', 'Other')], default='other', max_length=30)),
                ('label', models.CharField(blank=True, help_text="Short label or note (e.g. 'Light background variant').", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark this as the default image for its type.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='office.company')),
                ('image', models.ForeignKey(blank=True, help_text='Select from the shared Image library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_images', to='images.image')),
            ],
            options={
                'verbose_name': 'Company Image',
                'verbose_name_plural': 'Company Images',
                'ordering': ['image_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('ceo', 'CEO / Managing Director'), ('coo', 'COO / Operations Director'), ('cfo', 'CFO / Finance Director'), ('sales', 'Sales & Marketing'), ('legal', 'Legal & Compliance'), ('customer_service', 'Customer Service'), ('technical', 'Technical / Engineering'), ('admin', 'Administration'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, help_text="Job title as displayed publicly (e.g. 'Head of Sales').", max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show this person on the public-facing website.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='office.company')),
                ('portrait', models.ForeignKey(blank=True, help_text='Profile photo from the shared Image library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person_portraits', to='images.image')),
                ('user', models.ForeignKey(blank=True, help_text="Link to a UserAccount. When set, the person's name and email are inherited from that account.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contact_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'ordering': ['order', 'role'],
            },
        ),
    ]
