# Generated by Django 5.2.11 on 2026-02-24 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0001_initial'),
        ('images', '0006_alter_image_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablehomespage',
            name='cta_button_link',
        ),
        migrations.RemoveField(
            model_name='availablehomespage',
            name='cta_button_text',
        ),
        migrations.RemoveField(
            model_name='availablehomespage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='availablehomespage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='availablehomespage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='availablehomespage',
            name='hero_title',
        ),
        migrations.CreateModel(
            name='AvailableHome',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, help_text='Price in KES format', max_length=100)),
                ('beds', models.PositiveIntegerField(blank=True, default=0)),
                ('baths', models.PositiveIntegerField(blank=True, default=0)),
                ('sqft', models.PositiveIntegerField(blank=True, default=0, help_text='Square footage')),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('reserved', 'Reserved')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_homes', to='images.image')),
            ],
            options={
                'verbose_name': 'Available Home',
                'verbose_name_plural': 'Available Homes',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableHomesCTASection',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default="Didn't find what you're looking for?", max_length=200)),
                ('description', models.TextField(blank=True, default='We can design and build a bespoke home specifically for you on your preferred piece of land.')),
                ('button_text', models.CharField(blank=True, default='LEARN ABOUT CUSTOM BUILD', max_length=100)),
                ('button_link', models.CharField(blank=True, default='/process/', max_length=200)),
                ('available_homes_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta_section', to='available_homes.availablehomespage')),
            ],
            options={
                'verbose_name': 'Available Homes CTA Section',
                'verbose_name_plural': 'Available Homes CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='AvailableHomesHeroSection',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Available Homes For Sale', max_length=200)),
                ('description', models.TextField(blank=True, default="High-quality homes built by TrustBuildUrban for immediate purchase. Move-in ready residences in Kenya's most sought-after neighborhoods.")),
                ('available_homes_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='available_homes.availablehomespage')),
            ],
            options={
                'verbose_name': 'Available Homes Hero Section',
                'verbose_name_plural': 'Available Homes Hero Sections',
            },
        ),
    ]
