# Generated by Django 5.2.11 on 2026-02-24 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0002_remove_availablehomespage_cta_button_link_and_more'),
        ('images', '0006_alter_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehome',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the property'),
        ),
        migrations.CreateModel(
            name='AvailableHomeImage',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='available_homes.availablehome')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_home_images', to='images.image')),
            ],
            options={
                'verbose_name': 'Available Home Image',
                'verbose_name_plural': 'Available Home Images',
            },
        ),
    ]
