# Generated by Django 5.2.11 on 2026-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0003_availablehome_description_availablehomeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehome',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
