# Generated by Django 5.2.11 on 2026-02-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0004_availablehome_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom_information', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Bathroom Information',
                'verbose_name_plural': 'Bathroom Information',
            },
        ),
        migrations.CreateModel(
            name='BedroomInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom_information', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Bedroom Information',
                'verbose_name_plural': 'Bedroom Information',
            },
        ),
        migrations.CreateModel(
            name='GarageAndParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_and_parking', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Garage and Parking',
                'verbose_name_plural': 'Garage and Parking',
            },
        ),
        migrations.CreateModel(
            name='HeatingAndCooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_and_cooling', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Heating and Cooling',
                'verbose_name_plural': 'Heating and Cooling',
            },
        ),
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_features', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Interior Features',
                'verbose_name_plural': 'Interior Features',
            },
        ),
        migrations.CreateModel(
            name='KitchenAndDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_and_dining', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Kitchen and Dining',
                'verbose_name_plural': 'Kitchen and Dining',
            },
        ),
        migrations.CreateModel(
            name='OtherRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_rooms', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Other Rooms',
                'verbose_name_plural': 'Other Rooms',
            },
        ),
        migrations.CreateModel(
            name='OutdoorSpaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_spaces', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Outdoor Spaces',
                'verbose_name_plural': 'Outdoor Spaces',
            },
        ),
        migrations.CreateModel(
            name='UtilitiesAndGreenEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities_and_green_energy', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Utilities and Green Energy',
                'verbose_name_plural': 'Utilities and Green Energy',
            },
        ),
    ]
