# Generated by Django 5.2.11 on 2026-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0005_bathroominformation_bedroominformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoorspaces',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
