# Generated by Django 5.2.11 on 2026-02-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("available_homes", "0006_outdoorspaces_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availablehomeimage",
            name="image_url",
        ),
    ]
