# Generated by Django 5.2.11 on 2026-02-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("available_homes", "0007_remove_availablehomeimage_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availablehome",
            name="image",
        ),
        migrations.RemoveField(
            model_name="availablehome",
            name="image_url",
        ),
    ]
