# Generated by Django 5.2.11 on 2026-02-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0008_remove_availablehome_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Buyer's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Buyer's last name", max_length=100)),
                ('email', models.EmailField(help_text="Buyer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Buyer's phone number", max_length=20)),
                ('offer_amount', models.CharField(help_text='Offer amount in KES', max_length=50)),
                ('financing_type', models.CharField(choices=[('cash', 'Cash'), ('mortgage', 'Mortgage'), ('exchange', 'Property Exchange'), ('installment', 'Installment'), ('other', 'Other')], default='mortgage', help_text='How the buyer plans to finance the purchase', max_length=20)),
                ('is_first_time_buyer', models.BooleanField(default=False, help_text="Whether this is the buyer's first home purchase")),
                ('message', models.TextField(blank=True, help_text='Additional message or terms')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('counter_offer', 'Counter Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The property being offered on', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Property Offer',
                'verbose_name_plural': 'Property Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(help_text="User's last name", max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('phone', models.CharField(help_text="User's phone number", max_length=20)),
                ('preferred_date', models.DateField(help_text='Preferred date for showing')),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (9AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 6PM)'), ('any', 'Any Time')], default='any', help_text='Preferred time slot for showing', max_length=50)),
                ('is_first_time_buyer', models.BooleanField(default=False, help_text="Whether this is the user's first home purchase")),
                ('message', models.TextField(blank=True, help_text='Additional message or questions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The property the user wants to view', on_delete=django.db.models.deletion.CASCADE, related_name='showing_requests', to='available_homes.availablehome')),
            ],
            options={
                'verbose_name': 'Showing Request',
                'verbose_name_plural': 'Showing Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
