# Generated by Django 5.2.11 on 2026-02-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_homes', '0009_propertyoffer_showingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehome',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g. -1.286389). Right-click any spot in Google Maps and copy the first number shown.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='availablehome',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g. 36.817223). Right-click any spot in Google Maps and copy the second number shown.', max_digits=9, null=True),
        ),
    ]
