# Generated by Django 5.2.11 on 2026-02-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('story_eyebrow', models.CharField(blank=True, max_length=100)),
                ('story_heading', models.CharField(blank=True, max_length=200)),
                ('story_description_1', models.TextField(blank=True)),
                ('story_description_2', models.TextField(blank=True)),
                ('story_image_url', models.URLField(blank=True)),
                ('story_quote', models.TextField(blank=True)),
                ('years_experience_value', models.CharField(blank=True, max_length=20)),
                ('projects_completed_value', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
            bases=('pages.page',),
        ),
    ]
