# Generated by Django 5.2.11 on 2026-02-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='projects_completed_value',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_description_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_description_2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_eyebrow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_image_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_quote',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='years_experience_value',
        ),
        migrations.CreateModel(
            name='CorePillarsSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='The TrustBuild Standards', max_length=100)),
                ('heading', models.CharField(blank=True, default='Our Core Pillars', max_length=200)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_pillars_sections', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Core Pillars Section',
                'verbose_name_plural': 'Core Pillars Sections',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='Our Story', max_length=100)),
                ('heading', models.CharField(blank=True, default='Excellence in Construction, Built on Trust.', max_length=200)),
                ('description', models.TextField(blank=True, default="<p>Founded on the principle of radical transparency, TrustBuild Urban has become the premier choice for Kenyans living abroad and local high-end homeowners. We recognized a massive gap in the market: the lack of corporate accountability in residential construction. Our mission is to provide a seamless, stress-free building experience where quality is never compromised, and every shilling is accounted for. We don't just build houses; we build legacies.</p><p>Our mission is to provide a seamless, stress-free building experience where quality is never compromised, and every shilling is accounted for. We don't just build houses; we build legacies.</p>")),
                ('quote', models.TextField(blank=True, default="Transparency isn't a buzzword; it's our core architecture.")),
                ('about_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='about.aboutpage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_hero_sections', to='images.image')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True, help_text='SVG icon code')),
                ('core_pillars_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='about.corepillarssection')),
            ],
            options={
                'verbose_name': 'Pillar',
                'verbose_name_plural': 'Pillars',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('value', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.herosection')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
