# Generated by Django 5.2.11 on 2026-02-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutpage_projects_completed_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image_alt',
            field=models.CharField(blank=True, default='Architecture Team', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
