# Generated by Django 5.2.11 on 2026-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_herosection_image_alt_herosection_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Page description for SEO', max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Page title for SEO', max_length=70),
        ),
    ]
