# Generated by Django 5.2.11 on 2026-02-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutpage_meta_description_aboutpage_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_title',
        ),
    ]
