# Generated by Django 5.2.11 on 2026-02-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='portfolio_description',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='portfolio_heading',
        ),
        migrations.CreateModel(
            name='PortfolioHeader',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, default='Our Portfolio', max_length=200)),
                ('description', models.TextField(blank=True, default='A showcase of architectural brilliance and construction precision across Nairobi, Kiambu, and beyond.')),
                ('portfolio_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_section', to='portfolio.portfoliopage')),
            ],
            options={
                'verbose_name': 'Portfolio Header',
                'verbose_name_plural': 'Portfolio Headers',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProjectsSection',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learn_more_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('portfolio_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_sections', to='portfolio.portfoliopage')),
            ],
            options={
                'verbose_name': 'Portfolio Projects Section',
                'verbose_name_plural': 'Portfolio Projects Sections',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProjectCategory',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('projects_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portfolio.portfolioprojectssection')),
            ],
            options={
                'verbose_name': 'Portfolio Project Category',
                'verbose_name_plural': 'Portfolio Project Categories',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('projects_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolioprojectssection')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('uuid', models.UUIDField(db_default=models.Func(function='uuidv7'), db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_project_images', to='images.image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioproject')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
