# Generated by Django 5.2.11 on 2026-02-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioheader_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprojectcategory',
            name='projects_section',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.portfolioprojectcategory'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='highlight_project',
            field=models.BooleanField(default=False),
        ),
    ]
