# Generated by Django 5.2.11 on 2026-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolioprojectcategory_projects_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planning', 'Planning'), ('on_hold', 'On Hold')], max_length=50),
        ),
    ]
