# Generated by Django 5.2.11 on 2026-02-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioproject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='projects_section',
        ),
    ]
