# Generated by Django 5.2.11 on 2026-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_portfolioproject_projects_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True),
        ),
    ]
